//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoGamesStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.InVoice = new HashSet<InVoice>();
        }
    
        public string OrderId { get; set; }
        public string ProductId { get; set; }
        public string Quantity { get; set; }
        public string Log_In { get; set; }
        public string fecha { get; set; }
        public string OrderStatusId { get; set; }
        public string CartId { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Clients Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InVoice> InVoice { get; set; }
        public virtual Products Products { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
    }
}
